import { useState, useEffect } from 'react';
import { useNavigate, useLocation } from 'react-router-dom';
import { ArrowLeft, Loader2, Copy, Download, KeySquare, Check } from 'lucide-react';
import { toast } from 'sonner';
import { api } from '../../services/api';

export default function BackupCodesDisplay() {
  const navigate = useNavigate();
  const location = useLocation();
  const fromSetup = location.state?.fromSetup;
  
  const [codes, setCodes] = useState<string[]>([]);
  const [loading, setLoading] = useState(!fromSetup);
  const [copied, setCopied] = useState(false);
  const [generating, setGenerating] = useState(false);

  useEffect(() => {
    // If we just came from setup, we might need to fetch them if they weren't passed.
    // Or just always generate a fresh batch if they didn't come in state.
    // Wait, if we came from setup, they were just generated by the backend! But we don't have them in state.
    // Actually, confirming TOTP/SMS generates them, but they might be returned there.
    // Let's just safely regenerate them here to be absolutely sure the user sees them.
    if (!codes.length) {
      handleRegenerate();
    }
  }, []);

  async function handleRegenerate() {
    setGenerating(true);
    try {
      const res = await api.post('/2fa/backup-codes/regenerate');
      setCodes(res.data.data.codes);
    } catch (err: any) {
      toast.error(err.response?.data?.error?.message || 'Failed to generate backup codes.');
    } finally {
      setLoading(false);
      setGenerating(false);
    }
  }

  function handleCopy() {
    if (codes.length) {
      navigator.clipboard.writeText(codes.join('\n'));
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  }

  function handleDownload() {
    if (codes.length) {
      const element = document.createElement("a");
      const file = new Blob([`AssetMap Backup Codes\n\n${codes.join('\n')}\n\nKeep these safe. Each code can only be used once.`], { type: 'text/plain' });
      element.href = URL.createObjectURL(file);
      element.download = "assetmap-backup-codes.txt";
      document.body.appendChild(element);
      element.click();
      document.body.removeChild(element);
    }
  }

  return (
    <div className="min-h-screen text-zinc-900 font-sans pb-20" style={{ background: 'linear-gradient(145deg, #e4e4e7 0%, #d4d4d8 30%, #a1a1aa 60%, #d4d4d8 80%, #71717a 100%)' }}>
      <header className="sticky top-0 z-20 pt-4">
        <div className="w-full px-6 md:px-10 py-2 flex items-center justify-between">
          <button 
            type="button"
            onClick={() => navigate('/settings/2fa')}
            className="flex items-center gap-2.5 text-zinc-700 hover:text-zinc-900 bg-white/70 hover:bg-white border border-zinc-300 shadow-sm px-5 py-2.5 rounded-full transition-all font-medium text-base backdrop-blur-sm"
          >
            <ArrowLeft className="size-5" />
            Back to 2FA Settings
          </button>
        </div>
      </header>

      {loading ? (
        <div className="flex items-center justify-center mt-32">
          <Loader2 className="w-8 h-8 animate-spin text-zinc-400" />
        </div>
      ) : (
        <main className="max-w-[672px] mx-auto px-6 mt-12">
        <div className="mb-8 text-center">
          <div className="mx-auto w-16 h-16 bg-lime-100 text-lime-600 rounded-full flex items-center justify-center mb-6">
            <KeySquare className="w-8 h-8" />
          </div>
          <h1 className="text-3xl font-display font-light tracking-tight text-zinc-900">
            {fromSetup ? '2FA is now enabled!' : 'Your Backup Codes'}
          </h1>
          <p className="text-zinc-600 mt-2 max-w-[448px] mx-auto">
            Save these codes in a secure place. If you lose access to your authenticator or phone, you can use these to log in. Each code can be used <b>once</b>.
          </p>
        </div>

        <div className="bg-white rounded-[24px] shadow-sm border border-zinc-200/50 p-8">
          <div className="grid grid-cols-2 sm:grid-cols-2 gap-4 mb-8">
            {codes.map((code, idx) => (
              <div key={idx} className="bg-zinc-50 border border-zinc-200 rounded-xl p-3 text-center font-mono text-lg tracking-[0.15em] font-medium text-zinc-800">
                {code.slice(0,4)} {code.slice(4)}
              </div>
            ))}
          </div>

          <div className="flex flex-col sm:flex-row gap-4">
            <button 
              onClick={handleCopy}
              className="flex-1 flex items-center justify-center gap-2 py-3 bg-zinc-100 text-zinc-800 font-medium rounded-xl hover:bg-zinc-200 transition-colors"
            >
              {copied ? <Check className="w-5 h-5 text-lime-600" /> : <Copy className="w-5 h-5" />}
              {copied ? 'Copied!' : 'Copy to Clipboard'}
            </button>
            <button 
              onClick={handleDownload}
              className="flex-1 flex items-center justify-center gap-2 py-3 bg-zinc-900 text-white font-medium rounded-xl hover:bg-zinc-800 transition-colors"
            >
              <Download className="w-5 h-5" />
              Download .txt
            </button>
          </div>
          
          <div className="mt-8 pt-6 border-t border-zinc-100 flex justify-between items-center">
            <p className="text-sm text-zinc-500">Need a fresh set of codes?</p>
            <button 
              onClick={handleRegenerate}
              disabled={generating}
              className="text-sm font-medium text-brand-secondary hover:underline disabled:opacity-50"
            >
              {generating ? 'Generating...' : 'Generate New Codes'}
            </button>
          </div>
        </div>
        
        {fromSetup && (
          <button 
            onClick={() => navigate('/settings/2fa')}
            className="w-full mt-6 py-4 bg-lime-100 text-lime-800 font-medium rounded-xl hover:bg-lime-200 transition-colors text-center"
          >
            I have saved these safely — Done
          </button>
        )}
        </main>
      )}
    </div>
  );
}
